benchmarks:
  hwgptbench-s:
    - perplexity
    # - rtx2080_latencies
    - flops
    - params
  hwgptbench-m:
    - perplexity
    # - rtx2080_latencies
    - flops
    - params
  hwgptbench-l:
    - perplexity
    # - rtx2080_latencies
    - flops
    - params
prior_spec:
  - [good, 0, 0.01, null]
  # - [medium, 0, 0.125, null]
  - [bad, -1, 0, null]
kwargs:
  device: "rtx2080"