exp_dir: ablation_algos_20
output_dir: /home/soham/Master_Thesis/plots/ICLR/exp/
save_suffix: ablation_algos_mixed
avg_prior_label: mixed
priors_to_avg:
  - bad-good
  - good-bad
skip_non_avg: True
skip_opt:
  - NepsEtaPriorPriMO
  - NepsEtaPriorMFPriMO
  - NepsPriMO_Init10
  - NepsMOASHA_RS
skip_bench:
  - MOMFPark
  - hwgptbench-s
  - hwgptbench-m
  - hwgptbench-l
  - jahs-CIFAR10
  - jahs-ColorectalHistology
  - jahs-FashionMNIST
which_labels: ablation
which_plots:
  - hv
specific_fig_params:
  - xylabel_fontsize=20
  - ovrank_xsize=6
  - ovrank_ysize=4