exp_dir: ablation_init_20
output_dir: /home/soham/Master_Thesis/plots/ICLR/exp/
save_suffix: ablation_init_all_bad
skip_priors:
  - good-good
  - bad-good
  - good-bad
skip_bench:
  - MOMFPark
  - hwgptbench-s
  - hwgptbench-m
  - hwgptbench-l
  - jahs-CIFAR10
  - jahs-ColorectalHistology
  - jahs-FashionMNIST
which_labels: ablation_init
which_plots:
  - hv
specific_fig_params:
  - xylabel_fontsize=20
  - ovrank_xsize=6
  - ovrank_ysize=4