exp_dir: subset2
output_dir: /home/soham/Master_Thesis/ICLR/plots/exp/
skip_priors:
  - good-good
  - bad-good
  - good-bad
save_suffix: subset2_all_bad
skip_opt:
  - NepsMOASHA
  - NepsMOASHABO
  - NepsPriorMOASHA
skip_bench:
  - MOMFPark
  - hwgptbench-s
  - hwgptbench-m
  - hwgptbench-l
  - jahs-CIFAR10
  - jahs-ColorectalHistology
  - jahs-FashionMNIST
which_labels: "1"
which_plots:
  - hv
specific_fig_params:
  - bbox_to_anchor=(0.5, -0.08)
figsize:
  - 16
  - 8