exp_dir: all_naive_20
output_dir: /home/soham/Master_Thesis/ICLR/plots/exp/
skip_priors:
  - good-good
  - bad-good
  - good-bad
save_suffix: exp_naive_all_bad
skip_opt:
  - NepsPriMO
skip_bench:
  - MOMFPark
  - hwgptbench-s
  - hwgptbench-m
  - hwgptbench-l
  - jahs-CIFAR10
  - jahs-ColorectalHistology
  - jahs-FashionMNIST
which_labels: "1"
which_plots:
  - hv
specific_fig_params:
  - xylabel_fontsize=20
  - ovrank_xsize=6
  - ovrank_ysize=4