yaml_files:
  - configs/paper_configs/exp/exp_subset2_overall.yaml
  - configs/paper_configs/exp/exp_subset2_all_good.yaml
  - configs/paper_configs/exp/exp_subset2_mixed.yaml
  - configs/paper_configs/exp/exp_subset2_all_bad.yaml
output_dir: /home/soham/Master_Thesis/ICLR/plots/exp/
save_suffix: exp_subset2_all_rankings
file_type: pdf
figsize:
  - 16
  - 4
sub_labels:
  - Overall
  - All priors good
  - Mixed priors
  - All priors bad
remove_prior_annots: true
ylim: 4
cut_off_iteration: 20