exp_dir: subset1
output_dir: /home/soham/Master_Thesis/ICLR/plots/exp/
skip_non_avg: true
priors_to_avg:
  - bad-good
  - good-bad
avg_prior_label: mixed
save_suffix: subset1_mixed
skip_opt:
  - RandomSearchWithPriors
  # - NepsMOBO
skip_bench:
  - MOMFPark
  - hwgptbench-s
  - hwgptbench-m
  - hwgptbench-l
  - jahs-CIFAR10
  - jahs-ColorectalHistology
  - jahs-FashionMNIST
which_labels: "1"
which_plots:
  - hv
specific_fig_params:
  - bbox_to_anchor=(0.5, -0.12)
figsize:
  - 16
  - 8