exp_dir: hwgptbench_20
output_dir: /home/soham/Master_Thesis/ICLR/plots/extra/
skip_priors:
  - good-good
  - bad-good
  - good-bad
save_suffix: hwgptbench_prior_all_bad
skip_opt:
  - RandomSearch
  - NepsHyperbandRW
  - NepsRW
  - Optuna
  - SMAC_ParEGO
  - Nevergrad_EvolutionStrategy
  - NepsMOASHA
which_labels: "1"
which_plots:
  - hv
  - pareto
specific_fig_params:
  - bbox_to_anchor=(0.5, -0.12)
figsize:
  - 12
  - 4