yaml_files:
  - configs/paper_configs/extra/hwgptbench_nonprior_overall.yaml
  - configs/paper_configs/extra/hwgptbench_nonprior_all_good.yaml
  - configs/paper_configs/extra/hwgptbench_nonprior_mixed.yaml
  - configs/paper_configs/extra/hwgptbench_nonprior_all_bad.yaml
output_dir: /home/soham/Master_Thesis/ICLR/plots/extra/
save_suffix: hwgptbench_nonprior_all_rankings
file_type: pdf
figsize:
  - 16
  - 4
sub_labels:
  - Overall
  - All priors good
  - Mixed priors
  - All priors bad
remove_prior_annots: true
ylim: 6
cut_off_iteration: 20