exp_dir: hwgptbench_20
output_dir: /home/soham/Master_Thesis/ICLR/plots/extra/
skip_non_avg: true
priors_to_avg:
  - good-good
  - bad-good
  - bad-bad
  - good-bad
avg_prior_label: overall
save_suffix: hwgptbench_nonprior_overall
skip_opt:
  - RandomSearchWithPriors
  - NepsMOPriorband
  - NepsPiBORW
skip_bench:
  - MOMFPark
which_labels: "1"
which_plots:
  - hv
specific_fig_params:
  - bbox_to_anchor=(0.5, -0.12)
figsize:
  - 12
  - 4