exp_dir: hwgptbench_20
output_dir: /home/soham/Master_Thesis/ICLR/plots/extra/
skip_priors:
  - bad-good
  - bad-bad
  - good-bad
save_suffix: hwgptbench_nonprior_all_good
skip_opt:
  - RandomSearchWithPriors
  - NepsMOPriorband
  - NepsPiBORW
skip_bench:
  - MOMFPark
which_labels: "1"
which_plots:
  - hv
  - pareto
specific_fig_params:
  - bbox_to_anchor=(0.5, -0.12)
figsize:
  - 12
  - 4